### ISSUE TITLE
To-Do 20 may

### ISSUE THREAD

**Issue by annechh** [annechh/FED1-Project-Exam-1#49]
- [x] fix welcome user
- [ ] set up edit page
- [x] add delete and edit buttons to index and post/index pages

**Comment by annechh** [comment]
Did not finish setting up edit page.
On to-do for next day
