### ISSUE TITLE
To-Do 21-22 may

### ISSUE THREAD

**Issue by annechh** [annechh/FED1-Project-Exam-1#53]
On post index

- [x] make edit and delete button only visable to admin
- [x] make edit button redirect to edit page

Made it so nobody can enter edit page without autorization

---

On post edit

- [x] be able to change image url
- [x] be able to change title
- [x] be able to change blog text 
- [x] be able to change Save changes

Struggeling with save, no ID,
to do 22 may

- [ ] consider using localStorage for ID
